name: CD Python 

on:
 push:
 workflow_dispatch:

jobs:
 ci-cd:
  runs-on: ubuntu-latest
  env:
   DOCKER_IMAGE: pittasairam/flask-api-python-app
   
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2
 
    - name: Login to Docker
      uses: docker/login-action@v3.3.0
      with:
       username: ${{secrets.DOCKER_USERNAME1}}
       password: ${{secrets.DOCKER_PASSWORD1}}
   
    - name: Build docker image
      run: |
       docker build -t $DOCKER_IMAGE:${{github.sha}} .
       docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
       
    - name: Push docker image
      run: |
       docker push $DOCKER_IMAGE:${{github.sha}}
       docker push $DOCKER_IMAGE:latest

       
    - name: Setup Kubectl for kubernetes
      uses: azure/setup-kubectl@v3
      with:
       version: 'latest'
    - name: Setup Minikube
      run: |
       minikube start
       kubectl config use-context minikube
       
    - name: Deploy to Kubernetes
      run: |
       kubectl apply  -f k8s/deployment.yml
       kubectl apply -f k8s/service.yml
